### ISSUE TITLE
MAX in AVERAGE funkciji

### ISSUE THREAD

**Issue by jakamun** [jakamun/Avtomobilizem#2]
Pozdravljeni,

težavo imamo pri SQL stavku. Radi bi v tabelo ponudba dodali stolpec, kjer bi bila pokazana najvišja trenutna ponujena cena za določen avtomobil. Za vsak avto bi radi pokazali najvišjo ponudbo, ki je bila ponujena. Podobno bi radi v tabelo ocena_cenilca dodali stolpec ocena, ki bi se avtomatsko spreminjala glede na nove vnose ocen.

uporabniško ime in geslo za dostop v aplikacijo:up_ime: LokaMaka,geslo: fasada

SQL stavek, ki smo ga sestavili do sedaj (za prvi primer):
SELECT id_avto, znamka, model, gorivo, prevozeni_kilometri, 
velikost_motorja, kw, ponujena_cena FROM ponudba
JOIN oseba ON ponudba.ponudnik = oseba.id_oseba 
JOIN avtomobil ON ponudba.avto = avtomobil.id_avto
JOIN model ON model.id_model = avtomobil.id_model
JOIN znamka ON znamka.id_znamka = model.id_znamka
WHERE username='LokaMaka'

**Comment by jaanos** [comment]
Takih stolpcev se ne dodaja v tabele, saj gre za izpeljane podatke. Do njih lahko pridete s poizvedbo v aplikaciji, lahko si pa pomagate tudi s pogledi (`VIEW`), ki se bodo tako obnašali kot dinamične tabele, ki potem lahko vsebujejo take stolpce.

Funkciji `MAX` in `AVERAGE` sta agregatni funkciji in se bosta navadno uporabili skupaj z `GROUP BY`. V podanem primeru torej maksimalno ponudbo dobite z `MAX(ponujena_cena)` - ker vas zanima maksimum za vsak avtomobil, bo treba pri `GROUP BY` podati `id_avto` in še vse ostale stolpce, ki so od njega odvisni (morda posredno preko modela in znamke).
