### ISSUE TITLE
Končan projekt

### ISSUE THREAD

**Issue by janrudof** [jakamun/Avtomobilizem#3]
Pozdravljeni,

naša skupina je zaključila projekt in Vas prosimo za potrditev, da se lahko prijavimo na ustni zagovor.

Lep pozdrav

**Comment by jaanos** [comment]
Opažam, da imate v `auth_public.py` svoje geslo s polnim dostopom do baze - namesto tega naj bodo tam podatki za prijavo z uporabnikom `javnost`, ki naj pa ima seveda ustrezne pravice (poleg `SELECT` na vseh tabelah še `INSERT` oziroma `UPDATE`, kjer je to potrebno). Svetujem, da @ztrojer svoje geslo na bazi zamenjaš, saj je sedaj za vekomaj objavljeno na internetu.

Na repozitoriju imate tudi mapi `__pycache__` in `.vscode`, ki pa tja ne sodijo, saj gre za avtomatsko generirane datoteke. Svetujem, da v `.gitignore` dodaste sledeče vrstice:
```gitignore
*.pyc
__pycache__/
.vscode/
```
ter prej omenjeni mapi pobrišete.

Ko naredite zahtevek `POST` (in ob tem morda spremenite podatke v bazi), je dobra praksa, da po uspešni transakciji naredite preusmeritev na stran z zahtevkom `GET` - osveževanja strani potem ne bo sprožilo še enega zahtevka `POST` in spreminjanja baze. Tako npr. ni potrebno podvajati kode iz `avto_get` v `avto_post` - v slednji funkciji naredite samo vstavljanje v bazo (s predhodnimi preverbami); če je vse v redu, potem naredite `redirect`. Po potrebi lahko tudi strani z zahtevkom `GET` podaste dodatno sporočilo, npr.
```python
redirect("/avto/%s/?%s" % (x, urlencode({"napaka": 'Ocena mora biti med 1 in 10.'})))
```
Do podane vrednosti potem dostopate z `request.query.napaka`.

Mimogrede, opažam, da če ocenim avtomobil, se izpiše več podanih ocen avtomobila, kot če samo pogledam avtomobil ali oddam ponudbo. V primerih, ko ocenjevanje ali oddajanje ponudb ni več mogoče, bo najbolje, da ustreznih polj sploh ne prikažete (npr. če se je dražba iztekla).

Pri sporočilih ni čisto jasno, zakaj so ločena na več delov, poleg tega pa se nekatera sporočila ponovijo. Če želite ločiti sporočila po sogovorniku, potem bo najbolje, da naredite slovar, katerega ključi bodo sogovorniki, pri vsakem pa je potem seznam sporočil. V `get_komentar` greste torej čez sporočila in ustvarite ta slovar, v predlogi pa greste potem čez slovar in čez vsak seznam v slovarju, pri čemer pred seznamom sporočil izpišete, za katerega sogovornika gre (morda se lahko še malo poigrate s prikazom sporočil). V poizvedbi dajte `ORDER BY` na zunanji `SELECT`, saj nimate zagotovila, da se bo vrstni red ohranil, ko delate `JOIN`.

**Comment by ghost** [comment]
Naredili smo popravke, prosimo Vas da pregledate popravljeno in potrdite ustreznost.

Lep pozdrav

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenite za termin zagovora, če se seveda še niste. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Opazil sem sicer, da odjava ne deluje - prikaže se sicer stran za prijavo, še vedno pa je mogoče obiskati ostale strani. Problem je tukaj:
https://github.com/jakamun/Avtomobilska-drazba/blob/355b882f252896f9170cd827657bf3de0ec10153/baza.py#L296
Ker pri nastavljanju piškotka podajate parameter `path='/'`, bo treba ta parameter podati tudi tukaj. Svetujem sicer, da iz strani za prijavo, registracijo in zamenjavo gesla naredite preusmeritev na začetno stran, če je uporabnik že prijavljen.

Še to: geslo, podano pri registraciji, se ne nastavi, saj imata obe polji za geslo ime `password`, medtem ko v `baza.py` pričakujete `password1` in `password2`. Pri zamenjavi gesla se pa niti ne preveri, ali se podani gesli ujemata (polji imata spet isto ime).

**Comment by jakamun** [comment]
Popravili smo opažene napake. Prosimo če lahko posodobite povezavo.

Lep pozdrav

**Comment by jaanos** [comment]
Sem posodobil.

Še dve pripombi bolj estetske narave:
* Pri zamenjavi gesla to v poljih ni skrito.
* Če se pri registraciji vnese obstoječ račun, pride do napake - lahko bi se izpisala kaka uporabniku bolj prijazna napaka.
